export const Brand=[
{
    id:1,
    title:"STATE"
},
{
    id:2,
    title:"COOPER"
},
{
    id:3,
    title:"BARDOT"
},
{
    id:4,
    title:"ALFANI"
},
{
    id:5,
    title:"CECE"
},
{
    id:6,
    title:"DONNA RICCO"
},
]
export const Dress=[
    {
        id:1,
        title:"SHORT"
    },
    {
        id:2,
        title:"KNNE LENGHT"
    },
    {
        id:3,
        title:"HIGHT LOW"
    },
    {
        id:4,
        title:"LONG "
    },
    {
        id:5,
        title:"MIDI"
    },
 
    ]

    export const Size=[
        {
            id:1,
            title:"OSF"
        },
        {
            id:2,
            title:"C32"
        },
        {
            id:3,
            title:"B34"
        },
        {
            id:4,
            title:"A72"
        },
        {
            id:5,
            title:"C88"
        },
        {
            id:6,
            title:"D62"
        },
        {
            id:7,
            title:"O65"
        },
        {
            id:8,
            title:"C90"
        },
        {
            id:9,
            title:"B39"
        },
        {
            id:10,
            title:"A70"
        },
        {
            id:11,
            title:"C18"
        },
        {
            id:12,
            title:"D22"
        },
        {
            id:13,
            title:"A27"
        },
        {
            id:14,
            title:"C39"
        },
        {
            id:15,
            title:"B34"
        },
        {
            id:16,
            title:"A72"
        },
        {
            id:17,
            title:"C88"
        },
        {
            id:18,
            title:"D62"
        },
        {
            id:19,
            title:"C80"
        },
        {
            id:10,
            title:"D82"
        },
        ]


        export const Color=[
            {
                id:1,
                title:"black"
            },
            {
                id:2,
                title:"green"
            },
            {
                id:3,
                title:"red"
            },
            {
                id:4,
                title:"yellow"
            },
            {
                id:5,
                title:"orange"
            },
            {
                id:6,
                title:"blue"
            },
            {
                id:7,
                title:"gray"
            },
            {
                id:8,
                title:"red"
            },
            
            {
                id:9,
                title:"green"
            },
            {
                id:10,
                title:"white"
            },
            {
                id:11,
                title:"black"
            },
            {
                id:12,
                title:"blue"
            },
        ]


   