export const productData = [
    { data:"W26" },
    { data:"W27" },
    { data:"W28" },
    { data:"W29" },
    { data:"W30" },
    { data:"W31" },
    // { data:"W32" },
    // { data:"W33" },
    // { data:"W34" },
    // { data:"W35" },
    // { data:"W36" },
    // { data:"W31" },
    // { data:"W32" },
    // { data:"W27" },
    // { data:"W32" },
    // { data:"W31" },
    // { data:"W32" },
    // { data:"W32" },
    // { data:"W27" },
    // { data:"W31" },
]